name: Deploying docs

on:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - 'genetwork/docs/**'
      - 'environment.yml'
      - 'genetwork/poetry.lock'
      - 'genetwork/pyproject.toml'
      - '.github/workflows/docs.yml'

# env for all jobs
env:
  CONDA_CACHE_DIR: ~/conda_pkgs_dir
  POETRY_CACHE_DIR: ~/.cache/pypoetry
  PIP_CACHE_DIR: ~/.cache/pip
  # increase this value to manually reset cache
  CACHE_NUMBER: 0

jobs:
  deploy-docs:
    name: Deploy docs
    # better to use pinned version here
    runs-on: ubuntu-20.04
    defaults:
      run:
        # necessary for conda to work
        shell: bash -l {0}
    steps:
      - # get repository code
        name: Checkout code
        uses: actions/checkout@v2
      - # get conda, poetry and pip cache (persistent between runs)
        name: Cache packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CONDA_CACHE_DIR }}
            ${{ env.POETRY_CACHE_DIR }}
            ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pkgs-${{ env.CACHE_NUMBER }} }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - # set up pip cache
        name: Set up pip cache
        run: python3 -m pip config set global.cache-dir ${{ env.PIP_CACHE_DIR }}
      - name: Install poetry
        run: python3 -m pip install poetry
      - # set up poetry cache
        name: Set up poetry cache
        run: poetry config cache-dir ${{ env.POETRY_CACHE_DIR }}
      - # create and activate conda environment
        name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: genetwork
          environment-file: environment.yml
          # necessary for caching to work
          use-only-tar-bz2: true
      - name: Install docs tools
        working-directory: genetwork
        # we need to install all base dependencies, waiting for https://github.com/python-poetry/poetry/issues/1644
        run: poetry install --no-root --extras docs
      - name: Deploy docs
        working-directory: genetwork/docs
        run: mkdocs gh-deploy --force