name: protosound

# conda-forge used only if packages not found in defaults
channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.9.4
  - pip==21.1.1
  - pip:
    - -r file:requirements.txt
    - -e protosound[dev]