version: "3.9"

services:
  postgres:
    build:
      context: ./database/postgres/
    ports:
      - "${POSTGRES_MAPPED_PORT:-5432}:5432"
    environment:
      - "POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-postgres}"
      - "POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD:-app}"
  pgadmin:
    build:
      context: ./database/pgadmin/
      args:
        - "PGADMIN_ADMIN_PASSWORD=${PGADMIN_ADMIN_PASSWORD:-admin}"
    ports:
      - "${PGADMIN_MAPPED_PORT:-5433}:80"
    environment:
      - "PGADMIN_POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-postgres}"
    depends_on:
      - postgres
  superset:
    build:
      context: ./database/superset/
    ports:
      - "${SUPERSET_MAPPED_PORT:-5434}:8088"
    environment:
      - "SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD:-admin}"
      - "SUPERSET_POSTGRES_USER=app"
      - "SUPERSET_POSTGRES_PASSWORD=${POSTGRES_APP_PASSWORD:-app}"
      - "SUPERSET_POSTGRES_HOST=postgres"
      - "SUPERSET_POSTGRES_PORT=5432"
      - "SUPERSET_POSTGRES_DATABASE=retrail"
    depends_on:
      - postgres
  retrapi:
    build:
      context: ./api/retrapi/
    ports:
      - "${RETRAPI_MAPPED_PORT:-10000}:8080"
    environment:
      - "RETRAPI_POSTGRES_USER=app"
      - "RETRAPI_POSTGRES_PASSWORD=${POSTGRES_APP_PASSWORD:-app}"
      - "RETRAPI_POSTGRES_HOST=postgres"
      - "RETRAPI_POSTGRES_PORT=5432"
      - "RETRAPI_POSTGRES_DATABASE=retrail"
    depends_on:
      - postgres
  hoppscotch:
    build:
      context: ./api/hoppscotch/
    ports:
      - "${HOPPSCOTCH_MAPPED_PORT:-11000}:3000"
    depends_on:
      - retrapi
