version: "3.9"

services:
  postgres:
    build:
      context: ./database/postgres/
    ports:
      - "${POSTGRES_MAPPED_PORT:-5432}:5432"
    environment:
      - "POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-postgres}"
  pgadmin:
    build:
      context: ./database/pgadmin/
      args:
        - "PGADMIN_ADMIN_PASSWORD=${PGADMIN_ADMIN_PASSWORD:-admin}"
    ports:
      - "${PGADMIN_MAPPED_PORT:-5433}:80"
    environment:
      - "PGADMIN_POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-postgres}"
    depends_on:
      - postgres
