name:                elka-life
version:             0.1.0.0
author:              "Wojciech Krupski, Piotr Makaruk, Sebastian Pietras"

extra-source-files:
- README.md

description:         Text game about typical students life at EITI

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  elka-life:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elka-life
